version: '3.4'

services:
  webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5100:80"

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5200:80"

